default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: module_development
  primary_replica:
    <<: *default
    database: module_development
    replica: true
  module:
    <<: *default
    # username: module_root username for different users must be different
    database: module_backend 
    migrations_paths: db/module_backend_migrate
  module_replica:
    <<: *default
    # username: module_root username for different users must be different
    database: module_backend
    migrations_paths: db/module_backend_migrate
    replica: true

test:
  <<: *default
  database: module_test

production:
  <<: *default
  database: module_production
  username: module
  password: <%= ENV['module_DATABASE_PASSWORD'] %>
