default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: module_development
  primary_replica:
    <<: *default
    database: module_development
    replica: true
  module:
    <<: *default
    # username: module_root username for different users must be different
    database: module_backend 
    migrations_paths: db/module_backend_migrate
  module_replica:
    <<: *default
    # username: module_root username for different users must be different
    database: module_backend
    migrations_paths: db/module_backend_migrate
    replica: true

test:
  primary:
    <<: *default
    database: module_test
  primary_replica:
    <<: *default
    database: module_test
    replica: true
  module:
    <<: *default
    # username: module_root username for different users must be different
    database: module_backend 
    migrations_paths: db/module_backend_migrate
  module_replica:
    <<: *default
    # username: module_root username for different users must be different
    database: module_backend
    migrations_paths: db/module_backend_migrate
    replica: true

production:
  primary:
    <<: *default
    database: module_production
    username: module
    password: <%= ENV['module_DATABASE_PASSWORD'] %>
  primary_replica:
    <<: *default
    database: module_production
    username: module
    password: <%= ENV['module_DATABASE_PASSWORD'] %>    
    replica: true
  module:
    <<: *default
    database: module_backend
    url: <%= ENV["HEROKU_POSTGRESQL_PURPLE_URL"] %>
    migrations_paths: db/module_backend_migrate
    username: module
    password: <%= ENV['module_DATABASE_PASSWORD'] %>
  module_replica:
    <<: *default
    # username: module_root username for different users must be different
    database: module_backend
    url: <%= ENV["HEROKU_POSTGRESQL_PURPLE_URL"] %>
    migrations_paths: db/module_backend_migrate
    username: module
    password: <%= ENV['module_DATABASE_PASSWORD'] %>
    replica: true