name: CI/CD Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: pradeep
          POSTGRES_PASSWORD: password@123
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.2

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        
    - name: Set up PostgreSQL
      env:
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |
        sudo ls /var/run/postgresql/.s.PGSQL.5432
        psql --host=localhost --username=pradeep --command="CREATE DATABASE module_test"
