name: Rails Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: primary_database
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      secondary_postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: secondary_database
        ports:
          - 5433:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.2

      - name: Set up PostgreSQL databases
        run: |
          cp config/database.yml.ci config/database.yml
          sed -i 's/primary_database/postgres/g' config/database.yml
          sed -i 's/secondary_database/postgres2/g' config/database.yml

      - name: Install dependencies
        run: bundle install --jobs 4 --retry 3

      - name: Set up primary database
        run: |
          bundle exec rails db:create RAILS_ENV=test
          bundle exec rails db:migrate RAILS_ENV=test

      - name: Set up secondary database
        run: |
          bundle exec rails db:create RAILS_ENV=test --database=secondary
          bundle exec rails db:migrate RAILS_ENV=test --database=secondary

      - name: Run tests
        run: bundle exec rspec
