name: PostgreSQL Workflow
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: pradeep
          POSTGRES_PASSWORD: password@123
          POSTGRES_DB: module_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PostgreSQL
      env:
        PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      run: |
        psql --host=localhost --username=pradeep --dbname=module_test --file=module_test.sql
